# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Composer install
          command: composer install -n --prefer-dist
          
      - run:
          name: Create reports folder
          command: mkdir -p /tmp/reports
          when: always

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      - run:
          name: Run Style Check
          command: vendor/bin/phpcs --report=junit --report-file=/tmp/reports/codestyle-junit.xml
          
      #- run:
      #    name: Run Unit tests
      #    command: phpunit --log-junit /tmp/reports/unittest-junit.xml
      
      - store_test_results:
          path: /tmp/reports
          
      - store_artifacts:
          path: /tmp/reports
